### PR TITLE
Fix INT 13h disk error vs unimplemented function

### LINKED ISSUE #52: ELKS boot of disk image fails
After commit of #50, I refreshed repo which had a couple other changes to it during time PR was being constructed.

Upon refresh, same ELKS image which works on #50 fails to boot with the following startup and error:
``` 
$ emu86 -I ../elks-gh/image/fd1440.bin 
info: disk image ../elks-gh/image/fd1440.bin (DCHS 0/80/2/18)
error: execute operation
AX 0800  BX 0004  CX 4F12  DX 0080  FL 0001
SI 0000  DI 0000  IP BBB4  SP 213E  BP 0000
DS 0000  ES 0000  CS 02C0  SS 1233

CF 1  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 0  DF 0  OF 0

02C0:BBB4  CD 13              int     $0x13
>
```
Screen Shot 2021-05-08 at 10 07 04 AM

Image attached: 
[fd1440.bin.zip](https://github.com/mfld-fr/emu86/files/6446146/fd1440.bin.zip)

Any ideas? I don't yet know if this has to do with 8-bit ADD fix or an INT 13h modification. I thought I'd ask before digging into it.

### PR DESCRIPTION
**Pull request by ghaerr**
@mfld-fr : This fixes the INT 13h handler, which was broken by a commit that returned 'err' rather than 0 for implemented subfunctions.

Fixes #52.

The implementation is a little tricky: programs may call INT 13h and get failure returned by CF, for instance, when querying drive status to determine if drive exists. This "error" condition cannot be interpreted by EMU86 as INT 13h failure.

Now, INT 13h only stops emulator on unimplemented functions.

Also fixes INT 13h AH=0 (reset).

### CODE REVIEW

File: rom-elks.c [hunk 1]
```diff
@@ -381,11 +382,11 @@ static int int_13h ()
 
 		default:
 			printf ("fatal: INT 13h: AH=%hxh not implemented\n", ah);
-			assert (0);
+			return err;
 		}
 
 	flag_set (FLAG_CF, err? 1: 0);
-	return err;
+	return 0;
```
Comment (mfld-fr) [inline rom-elks.c:389]: Interrupt hooks like this one **must** return an error to EMU86: 0 for OK, < 0 to stop the emulator, or > 0 to tell the emulator to try the real interrupt. This latest allows to implement only the functions that one wants to tweak if testing with a real BIOS, like a kind of 'BIOS overlay'.

File: rom-elks.c [hunk 2]
```diff
@@ -381,11 +382,11 @@ static int int_13h ()
 
 		default:
 			printf ("fatal: INT 13h: AH=%hxh not implemented\n", ah);
-			assert (0);
+			return err;
```
Comment (mfld-fr) [inline rom-elks.c:385]: No return here, please, but a break for structured programming.

**Review by mfld-fr — COMMENTED** [review]
> Now, INT 13h only stops emulator on unimplemented functions.

That could be discussed. EMU86 is primarily intended as a debugger, with no trust in the debugged code to handle errors. It should stop as soon as it detects such errors, like incorrect disk parameters. This for example helped much in finding the bug in the disk image management while testing *DOS in #30.

**Comment by mfld-fr** [comment]
By the way you could also remote INT 11h that ELKS does not need, as the hooks needed to boot *DOS will be implemented in another `rom-*.c`, as stated in #51.

File: rom-elks.c (hunk 2 above)
Comment (ghaerr) [reply rom-elks.c:385]: It is there because in this case, a -1 return is required.  I understand the structured programming, but this particular EMU86 interrupt handler requires a 0 return on implemented functions, regardless of whether there was a disk error or not (CF is for that).

I have a fix for #15, which uses the same approach: default case returns -1, otherwise 0. I don't think is is bad for these few cases, but you're welcome to rewrite how you want. I'm just trying to get ELKS to boot again so I can continue implementing functions.

**Comment by ghaerr** [comment]
> By the way you could also remote INT 11h that ELKS does not need, as the hooks needed to boot *DOS will be implemented in another rom-*.c, as stated in #51.

Yes, good idea. I will do that in a seperate PR.

File: rom-elks.c (hunk 1 above)
Comment (ghaerr) [reply rom-elks.c:389]: I understand completely. That's what the "return err" is for on line 385, which returns -1 on unimplemented subfunctions. This code does what you are requesting with EMU86.

Regarding incorrect disk parameters, ELKS won't boot without being able to query non-existent disks. It won't boot without this change.

The "default" case in the switch handles the request to find BIOS bugs.

**Comment by ghaerr** [comment]
> as the hooks needed to boot *DOS will be implemented in another rom-*.c, as stated in #51.

It would be nice to get this rom-elks.c working correctly before @cocus applies his changes to it for rom-.c, as this rom bios is currently buggy and rejects ELKS which boots on real ROM BIOS.

File: rom-elks.c (hunk 1 above)
Comment (mfld-fr) [reply rom-elks.c:389]: As you want, that's an `*-elks.c` file, so intented for ELKS maintainer.

**Comment by ghaerr** [comment]
Thanks.

I had prepared a enhancement/fix for issue #15, which removes the assert()'s from rom-elks.c and rom-advtech.c. However, this leaves the cases where the INT routine returns 0, but the "default switch" case (which indicates unimplemented) returns -1. Would you like me to post it? This would allow the emulator to reject the INT and stop emulation, but not termite emu86 itself.
